spring:
  datasource:
    druid:
      url: jdbc:mysql://39.96.54.49:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: smd521314
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 39.96.54.49
      database: blog
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 39.96.54.49:22122
upload:
  base-url: http://39.96.54.49/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg
